Repository kutovoys/xray-checker, pull requests merged in 2025-01, with the labels that each got.

#15 Overall improvements & fix Docker container
  .github/workflows/build-publish.yml
  .github/workflows/dockerhub-description.yml
  .github/workflows/release.yaml
  .gitignore
  .goreleaser.yaml
  Dockerfile
  README.md
  README_RU.md
  checker/checker.go
  config/config.go
  main.go
  models/proxy_config.go
  parser/parser.go
  runner/runner.go
  web/handlers.go
  web/template.go
  web/templates/index.html
  xray/template.go
  xray/templates/xray.json.tmpl
  xray/xray.go
Labels: enhancement

#17 feat: new check method: STATUS, new latency metric, simulate latency on endpoints
  README.md
  README_RU.md
  checker/checker.go
  config/config.go
  main.go
  metrics/metrics.go
  parser/parser.go
  web/handlers.go
  web/template.go
  web/templates/index.html
  xray/xray.go
Labels: enhancement

#18 feat: enhance subscription update handling and proxy checking logic
  main.go
Labels: enhancement

#21 feat: enhance metrics handling and configuration options
  README.md
  README_RU.md
  checker/checker.go
  config/config.go
  go.mod
  go.sum
  main.go
  metrics/metrics.go
  web/handlers.go
  web/template.go
  web/templates/index.html
Labels: enhancement

#22 Update README files to reflect GitHub Actions integration
  .github/screen/xray-checker.png
  README.md
  README_RU.md
  images/xray-checker.png
Labels: documentation, enhancement

#23 Bug fixes
  main.go
  metrics/metrics.go
  web/handlers.go
  web/template.go
  web/templates/index.html
Labels: bug, enhancement

#27 feat: initialize documentation for Xray Checker
  docs/.gitignore
  docs/.vscode/extensions.json
  docs/.vscode/launch.json
  docs/README.md
  docs/astro.config.mjs
  docs/package.json
  docs/pnpm-lock.yaml
  docs/public/favicon.svg
  docs/src/assets/houston.webp
  docs/src/content.config.ts
  docs/src/content/docs/configuration/check-methods.md
  docs/src/content/docs/configuration/envs.md
  docs/src/content/docs/configuration/subscription.md
  docs/src/content/docs/index.mdx
  docs/src/content/docs/integrations/metrics.md
  docs/src/content/docs/integrations/prometheus.md
  docs/src/content/docs/integrations/uptime-kuma.md
  docs/src/content/docs/intro/features.md
  docs/src/content/docs/intro/overview.md
  docs/src/content/docs/usage/cli.md
  docs/src/content/docs/usage/docker.md
  docs/src/content/docs/usage/github-actions.md
  docs/tsconfig.json
Labels: documentation

#26 feat: Refactored template and added VMESS
  models/proxy_config.go
  parser/parser.go
  xray/template.go
  xray/templates/xray.json.tmpl
  xray/xray.go
Labels: bug, enhancement

#34 Enhance index.html with additional proxy information
  web/templates/index.html
Labels: enhancement

#38 Feature/base url support
  config/config.go
  docs/src/content/docs/configuration/advanced-conf.md
  docs/src/content/docs/configuration/envs.md
  docs/src/content/docs/ru/configuration/advanced-conf.md
  docs/src/content/docs/ru/configuration/envs.md
  docs/src/content/docs/ru/usage/cli.md
  docs/src/content/docs/ru/usage/docker.md
  docs/src/content/docs/usage/cli.md
  docs/src/content/docs/usage/docker.md
  main.go
  web/handlers.go
  web/templates/index.html
Labels: documentation, enhancement
